---
output:
  pdf_document: default
  html_document: default
---
# 1. PERDE

     [Vak'a Ada'da ve üç fasıl da aynı salonda geçer:
     Ada'da bir köşkün alt katında bahçeye ve uzaktan denize nâzır bir yemek ve oturma odası,       sağda geniş camlı bir kapı.. Dipte bir kapı ve bir koridor solda merdiven yukarı çıkılan       bir medhal sağ birinci planda bir kapı ]

## Birinci Meclis

     (Pakize-Mukaddes]
     Perde açılmadan iki kadın kahkası, perde açılırken devam eder. Pakize Mukaddes sahnenin        önünde ayaktadırlar. Pakize'nin elinde mektuplar vardır.\
**Mukaddes** - (Gülmesi hafifleyerek) Aman yarabbi vallahi pek tuhaf çocuk Pakize Hanım.\
**Pakize**	- Değil mi? Pek eğlenceli mektup yazıyor. Bu yedinci mektubu yedisi de böyle.. Bundan yirmi gün önce kendisine bir rsmimi göndermiştim bak üçüncü mektubunda bunun için neler diyor (okur) "Süd kardeşim.. Resminiz geldi.. Aman yarabbi beni ne kadar sevindirdiniz.. Matbahdan [mutfaktan] kendimi kaptan köprüsüne dar attım artık kabıma sığamıyordum. fazla kaynamış süt gibi
kabarıyor, taşıyordum sevincimden bağırıyordum. Ve istiyordum ki hrkes benim sevincime uysun.. Artık başım geminin bacası gibi dumanlıydı, kalbime makine dairesinin bütün gürültüsü dolmuştu. Artık öyle istifi bozuk gemi gibi yan yatıp düşünmüyordum. Demek artık kimsesiz değilim diyordum. Ana yok, babam yok.. Onların da kimsesi yokmuş. Görüyorsunuz ya ben kimsesizlerin kimsesizi idim. Şimdi artık bir süt kardeşim var.. Yirmi beş sene evvel birbirine aynı süt ve meme ile birleşen dudaklarımız acaba yakın bir günde.. Aman kardeşim sakın bu sözüme fenâ bir manâ vermeyiniz.. Size karşı kardeşten başka.\
**Mukaddes** - (Gülerek) A-a bu adetâ bir aşk mektubu..\
**Pakize** - Ya onun gibi birşey. Pek eğlenceli yazıyor.. Zavallı Yaşar'cık\
**Mukaddes** - Herhalde süt ninenin oğlu pek şen bir çocuk..\
**Pakize** --Evet öyle galibâ!..\
**Mukaddes** - Galibâ mı?.. Süt kardeşini tanımıyor musun..\
**Pakize** - Hayır kardeşim tanımıyorum. Süt ninem öldüğü zaman ben altı yaşında idim. Onun yüzünü hayâl meyâl hatırlıyorum. Oğlu Yaşar da benim kadar bir bebekti.. Tam o zamanda merhûm babam memûriyetle Manisa'ya gitmek üzere idi. Yaşar'ı Dâr'ül-hayr'ın aşcısı Ömer Ağa isminde biri istemiş. Babam da süt ninemin hemşehrisi olan bu adamı kırmamak için çocuğu vermiş.. Aradan yirmi sene geçtiği halde şu tesâdüfe bakın süt ninemin çocuğu merhûm Ömer Ağa'nın evlatlığı Yaşar'cık asker oluyor. Hem de kocam gibi o da bahriyeye intisâb oluyor ve sonra günün birinde arayıp sorarak bu adrese anneme hitâben mektup yazıyor..\
**Mukaddes** - Ey sonra?..\
**Pakize** - Tabii annem ölmüş olduğundan bu mektuba ben cevap yazıyorum sonra artık muntazaman mektuplaşıyoruz. Zavallı çocuk bana hayatından askerliğinden bahseder hep aynı eğlenceli uslûbla.. O kadar ki belki yüzünü görsem tanıyamayacağım bir çocukla gâyet samîmî iki dost olduk.\
**Mukaddes** - Pekiyi ama sizde de onun resmi yok mu?\
**Pakize** - Var ama çocukken hep beraber ailece çektirilmiş bir resim. Düşün yirmi senelik solgun bir kağıt.. Yaşar bir buçuk senedir Trabzon'da imiş. Gemileri Karadeniz sahillerinde karakol yaparmış Son mektubunda nihâyet bir hafta kadar mezûniyet alabilidiğini ve Seyr-ü Sefain'in Akdeniz Vapuru'yla geleceğini bildiriyor. Bakalım Akdeniz ya bugün ya yarın gelecekmiş.. \
**Mukaddes** - A Akdeniz mi? Öyle ise Pakize'ciğim. Gözün aydın süt ninenin oğlu İstanbul'da..\
**Pakize** - Ne gibi?\
**Mukaddes** - Ne gibi olacak.. Akdeniz geleli dört saat oluyormuş. Sabahleyin erkenden bizim çamaşırcı Fatma söyledi.. O da oğlunu bekliyor..\
**Pakize** - Oo öyle ise hiç şüphe yok gelmiştir. Bugn olmazsa yarın sabah muhakkak buraya gelir.\

## Ikinci Meclis

     [Evvelkiler-Zeliha-Terzi]

**Zeliha** - Hanımefendi.. Beyefendinin esvabını getirdiler..\
**Pakize** - Peki buraya getirsinler.. (Zeliha çıkar)\
**Mukaddes** - Necdet Bey'in askerliği daha bitmedi mi kuzum. \
**Pakize** - Kocamın mı? Daha iki ayı var.. Onunki askerlik değil mirasyedilik kardeşim.. Hergün İstinye'de oturan miralayını motorla Heybeli'ye götürüp getirmekten başka bir iş yaptığı yok; motordan, otomobilden anlar diye bahriye erkanından miralay Rasim Bey'in maiyetine verdik bu rahatını da dayıma medyûndur [borçludur] ya.. Yüzünü bile görmediği damadına uzaktan yardım etti (giren terzi kızına) Ha bonjur matmazel beyin sivil kostümünü mü getirdiniz? Buraya bırakın. Faturası da yanınızda mı?\
**Terzi** - Evet efendim (uzatır) Efendim Beyefendi kostümünü bir def'a görmek isterlerse...\
**Pakize** - Beyefendi evde yok kızım bakar. Şayet bir kusur bulursa artık lütfen kendileri getirirler. Haydi yahut vaktiniz varsa biraz bekleyin yarıma kadar gelir..\
**Kız** - Peki efendim.. (çekilir) \
**Mukaddes** - (Pakize'nin terziye söz söylerken aldığı şiveye dikkat ederek) Ne o Paki[ze] galibâ yine kocanla aranız şeker renk?\
**Pakize** - Nasıl da bildin Mukaddes'ciğim.. Bu adama karşı içimde yenilmez bir kin var..\
**Mukaddes** -  A.. Aman yarabbi o nasıl söz kardeşim..\
**Pakize** - Evet bir aydan beri..\
**Mukaddes** - Kocana karşı, kin mi? Peki ama böyle kin besleyecek kadar ne yaptı da..\
**Pakize** - (Keserek) Ne yapacak? Evlendiğinin senesinde her erkek karısına ne yaparsa onu.. Beni aldattı.. Hem de bir kaldırım çiçeğine..\
**Mukaddes** - (Hayretinden gözlerini açıp fırlar) Ne? Necdet Bey seni aldattı mı?\ (Ağlayacak gibi) Aman yarabbi şu başıma gelen felakete bakınç Ah herşey aklıma gelirdi de bu gelmezdi işte.. Ah böyle inci gibi bir tazenin üstüne ha hem de sokak şırfıntılarıyla.. Ah..\
**Pakize** - (Mukaddes'in ani teessür ve ağlamasına şaşarak) Aman kardeşim yüreğine yazık nafile yere ne ağlıyorsun?..\
**Mukaddes** - Ah Pakize'ciğim.. Nasıl ağlamam.. Ya benimki de beni aldatırsa ben ne yaparım (Ağlamaya devam eder)\
**Pakize** - Hayır hayır ağlama.. Benim için niye kendini üzüyorsun? Eğer bir gün seninki de seni aldatırsa o vakit ağlarsın. Hem hayır niye ağlayacaksın.. Niye ağlayacağız? Erkeklerin hepsi bir kadının bir damla gözyaşına değmez. Onları aynı silahla yola getirmeli..\
**Mukaddes** - (Gözlerini silerek) Ama bilmezsin Pakize'ciğim  sanki kendi kocam üstüme hiyânet etmiş gibi içime dokundu eyy.. Peki ne oldu nasıl oldu da Necdet Bey'in hıyânetine vâkıf oldun.. Elinle mi yakaladın?.. \
**Pakize** - Ah nerede! Elimle tutsaydım hiç olmazsa hıncımı alırdım. Tutamadım fakat elimdeki isbât gâyet kuvvetli!.. 
(Dışarıdan Necdet'in sesi)\
**Necdet** - (Dışarıdan) Gel kızım.. Gel. Bir bakalım ne olur ne olmaz. Belki potları vardır.\
**Pakize** - Hah.. İşte Necdet.. Aman belli etmeyelim.. (Eliyle işaret)\
**Mukaddes** - A tabii kardeşim.. İşte (Susar kaşlarını çatar)\

## Üçüncü  Meclis 

     [Evvelkiler- Necdet- Roza-Zeliha]

**Necdet** - (Bahriye neferi, ellerinde yağlı eldivenler...) Aç aç matmazel.. (Hanımları görünce askerâne bir selamla) Hanımlar, merhabâ...(Kendi kendine güler, onların abûs çehrelerini görünce susar ve karısının o halini tabiî bularak) Ha.. (Mukaddes'e teveccühle) Efendim.. (Elini uzatır)\
**Mukaddes** - (Necdet'in uzattığı ele bakar.. Yarım bir dudak büküşle döner ve çok nazlı, dargın bir şive ile) Teşekkür ederim Necdet Bey, safâ geldiniz..\
 **Necdet** - <>.. Siz de safâ geldiniz Mukaddes Hanım, nasılsınız..\
**Mukaddes** - Teşekkür ederim\
 **Necdet** - Efendim.. Ha, oh oh.. Kemal Bey ne alemde?\
**Mukaddes** - Zevcim mi? İyidir kimbilir o da nerelerde?\
 **Necdet** - Tabiî kalemde değil mi efendim.. (Karısına) Eyy.. Pakize'ciğim (Pakize onun uzattığı eli reddeder)Ya..  Yine mi? (Her ikisine birden) Latîfe mi ediyorsunuz Allahaşkınıza?.. Ben girince niye böyle, döndünüz kaldınız canım? Ha anladım mutlaka beni çekiştiriyordunuz öyle mi? Mukaddes Hanım.. (Onların hallerine kızarak) Eyy iyi vallahi yine poyraz esiyor galibâ!!!..\
**Terzi Kızı** - (Bu hale güler) Hah..Hah..\
**Pakize** - (Yüksek sesle) Matmazel.. Burada komedi oynanmıyor. Lütfen terbiyenizi takınınız.. (Kocasına) Siz de çoluğa çocuğa gülünç oluyorsunuz.. Biraz daha ciddi olunuz.\
 **Necdet** - (Ciddi) Pekala! Pekala! (Terziye) Ha.. Bu mu matmazel ?.. Fena değil. Şöyle durun bakayım.. (Kızın arkasına ceketi koyar muayene eder)\
**Mukaddes** - (Yavaşca Pakize'ye) Kardeşim ben gideyim.. Bu dakikada hiç bir erkek yüzü görmeye tahammül edemeyeceğim.\
**Pakize** - Hakkın var Mukaddes'ciğim güle güle (şapka)\
**Necdet** - (Terzi ile meşgul) Ha bakın şuraları galibâ burası da biraz düşük.. Durun bakayım şöyle..\
**Pakize** - (Kocasına hiddetle) Beyefendi matmazel manken değil ceketinizi kendi sırtınızda muayene ediniz. Matmazel verin  o ceketi Zeliha'ya, Zeliha götür o kostümü beyin odasına haydi bakalım! (Zeliha çıkar) \
**Necdet** - An'allah ma'as-sabirin.. Peki matmazel siz de gidiniz teşekkür ederim. eğer bir kusuru varsa ben kendim mağazaya getiririm.\
**Terzi** - Pek efendim... Mersi... (Çıkar)\
**Mukaddes** -  (Gitmek üzere)  Allahaısmarladık Pakize'ciğim, bedbaht kardeşim!\
**Necdet** -  (Beraber) An'allah ma'asabirin\
**Pakize** -   Güle güle kardeşim.\
**Mukaddes** - Sizi beklerim iki gözüm... Beni unutmayın..\
**Pakize** - Hay hay gelirim kardeşim güle güle...\
**Necdet** - (Mukaddes'e) Gidiyor musunuz Mukaddes Hanım?..\
**Mukaddes** - Evet efendim.\
**Necdet** - Affedersiniz efendim. Müsâadenizle bir şey soracağım... \
**Mukaddes** - Buyurun...\
 **Necdet** - Sizi biraz değişmiş görüyorum. Sakın birşeye müteessir olmayınız.\
 **Necdet** - Sizi biraz değişmiş görüyorum. Sakın birşeye müteessir olmayınız.\
**Necdet** - (Şaşırarak) Ya!.. Söyleyiniz de bu teessürün yarısını ben alayım.\
**Mukaddes** -  Siz mi?.. Hım... Bir erkek...\
**Pakize** - (Mukaddes'in bir poy kırmasına  mani olmak için) Size ait değil beyefendi.. Bu kadar mütecessis olmayınız.. Biz kadınca dertleşiyorduk..\
**Necdet** - (Askerce bir selam) O halde affedersiniz.. Kemal Bey'e selam Mukaddes Hanım...\
**Mukaddes** - Söylerim.. Allahaısmarladık Pakize'ciğim. (Çıkar)\
**Pakize** - gule gule kardesim\

## Dördüncü Meclîs

     [Necdet-Pakize-Zeliha)

**Necdet** - (Karısına yaklaşarak) Pakize bu nedir, Mukaddes Hanım bana dargın mı kuzum?\
**Pakize** - Hayır hayır hemen üstünüze almayınız... Kabahatli olduğunuz ne kadar belli..\
**Necdet** - Ne demek?\
**Pakize** -  Tabiî baksanıza!.. Hemen alınıyorsunuz! (Sükût) \
**Necdet** - (Yaklaşarak) Peki karıcığım sen niye böylesin? Hâlâ mı Pakize hâlâ mı.. Bir ay oldu..\
**Pakize** - Rica ederim bana yaklaşmayınız..\
**Necdet** - Demek el'ân hırsınız geçmedi.. Seni kinci seni..\
**Pakize** - Hım!!..Kin mi? Size mi? Değmez ki.. İndimde o kadar ehemmiyetiniz yo ki nah işte şu resim gibi..\
**Necdet** - Resim gibi mi?\
**Pakize** - Evet bir resim bir gölge.. Siz yoksunuz..\
**Necdet** - Yok muyum? Öyle bir varım ki (sarılmak ister) karıcığım.\
**Pakize** - Ricâ ederim.\
**Necdet** -  Barışalım artık ya.. (Zeliha'nın geldiğini görerek çekilir)\
**Pakize** -  Sus hizmetçi.. Ne var Zeliha?\
**Zeliha** - Hanıefendi bir ricâm varda.. Onu ricâ edeceğim..\
**Necdet** - Ne imiş?\
**Pakize** - (Kocasının sesini bastırarak) Ne imiş bakalım?\
**Zeliha** - Bir hafta izin isteyecektimde..\
**Pakize** - Bir hafta izin mi.. Neden?\
**Zeliha** - Şey nişanlım annesinin evine gelmişde oraya gideceğim.\
**Pakize** - Nereden gelmiş?\
**Zeliha** - Askerden..\
**Necdet** - Senin nişanlın mı var kız?\
**Zeliha** - Ya.. Evet efendim. Ben..\
**Pakize** -  Bana söyle.. Eyy?..\
**Zeliha** -Evet efendim nişanlım var.. Ama iki de çocuğum var..\
**Pakize** - Çocuğun mu var?\
**Zeliha** - Evet ikiz.\
**Necdet** - Nişanlın? Çocuğun.. Nikâhtan evvel, hem de ikiz, bârî bir olsaydı değil mi Pakize?\
**Zeliha** - Ama efendim nişanlım  askerden gelince hemen nikâhlanacağız beni hâlâ seviyor.\
**Pakize** - Anlaşıldı.. Pekala.. Pekala..\
**Zeliha** - İzin verirseniz bu akşam gideceğim..\
**Pakize** - Bana bak kızım.. bir hafta izin olmaz sonra bize yemeği kim pişirecek. Aşcı kadın gelsin, ondan sonra..\
**Zeliha** - Efendim aşcı kadın yarın gelecek..\
**Pakize** -  Peki peki bakalım git sonra görüşürüz. (Kapı çalınır) Git bak kim geldi.\
**Zeliha** - Peki ama efendim?\
**Pakize** - (Sert) Sana ne diyorsam onu yap..\
**Zeliha** - Peki efendim.(Çıkar)\
**Necdet** - Zavallı kız sen de amma paylıyorsun ha.. Baksana nişanlısının çocukları da varmış. Hem de ikiz..\
**Pakize** - Evet, aşk meselelerinde beyefendinin yüreği yufkadır. Değil mi?\
**Necdet** - Ama Pakize'ciğim!\
**Pakize** - Kâfî!.. Evimizde bu kızdan başka kimse kalmadı. Kapıyı açmaktan başka bir işe yaramaya 12 yaşındaki Fatma'nın elinde mi kalacağız? Göndermeyeceğim işte.\
**Necdet** - Canım pekala aman..\
**Pakize** - Sus kızdırma beni..\

## Beşinci Meclîs

**Zeliha** -  Efendim elektrikçi gelmiş...\
**Pakize** - Hah geldi mi söyle gelsin..\
**Lami** - Bonjur efendim bonjur..\
**Necdet** - Bonjur Lami Bey elektrik instalasyonunun planını yapmak için geldiniz değil mi?\
**Lami** - Evet efendim; iki def'adır geliyorum. Sizi bulamıyorum. İyi oldu  bu tesâdüf.. Ki siz de,,\
**Pakize** - Affedersiniz beyim. Bu işler için benimle görüşeceksiniz efendi ile değil... Oturunuz efendim.\
**Lami** -  Peki efendim (Sükût)\
**Pakize** - Sizi rahatsız ettik affedersiniz.\
**Lami** - Beis yok efendim.. Mağazamda adamım var.. Şimdi efendim cereyanıbeldeden alacağız değil mi. Bu hus3usta lâzım gelen muâmelât-ı resmiye bitti değil mi efendim?\
**Necdet** -  Bu işler bitti efendim (Kalkarak)\
**Lami** -  Pek güzel efendim. Yukarı küçük köşke de.. elektrik alacaksınız değil mi efendim?\
**Necdet** - Hayır efendim.\
**Pakize** - evet efendim. Alacağız. Lami Bey. Bu evde yalnız benim reyim sorulur. Efendi burada hiç, hiç, hiçtir.\
**Necdet** - Oo Pakize ricâ ederim.. Çok oluyorsun artık..\
**Pakize** - Susunuz beyefendi.. Evet siz burada solda sıfırdan başka birşey değilsiniz (Necdet kendini hiddetle salıncak sandalyeye atarken Lami'e) Ne diyordum efendim? Evet her iki daireye de elektrik alacağız..\
**Lami** - Ya.. Hay hay efendim. Bundan kolay yok hanımefendi.\
**Necdet** - Sonra her odaya bir zil düğmesi istiyorum.\
**Lami** - Ya.. Hay hay bundan kolay birşey yok beyefendi.\
**Pakize** - (Şiddetle kalkarak) Ricâ ederim Lami Bey zil mil  istemez. Otel odaları gibi.. İstemiyorum. Hem bende bir mecmua var size göstermek için sakladım, orada elektiriğe dair çok zarîf resimler var, gideyim getireyim. (Çıkar)\



## Altıncı Meclîs 

     [Necmi-Lami]

**Lami** - (Yerinden kalkıp Necdet'in yanına gelerek) Affedersiniz efendim birşey soracağım..\
**Necdet** - Buyurun. \
**Lami** - Bu elektrik instalasyonu hakkında kimin sözünü dinşeyeceğim, sizin mi yoksa hanımefendinin mi?\
**Necdet** - Kimin mi? (vakfe [durma/durak yeri]) Lami Bey evli misiniz?\
**Lami** - Evet efendim... Üç seneden beri...\
**Necdet** - İyi... Karınızı aldatıyor musunuz?\
**Lami** - Karımı mı? Bilmiyorum efendim... Daha..\
**Necdet** - Ha.. Onu aldattığınız zaman -zira günün birinde mutlaka aldatacaksınız- sakın yakalanmayın.\
**Lami** - Vallahi.. (Gülerek) Bir parça şaşırdım da.. Ne söyleyeceğimi bilemiyorum.\
**Necdet** - Anlatayım. Lami Bey, patlıyorum tahammülüm kalmadı şu anda bir sırdaşa, derdimi dökecek bir arkadaşa muhtacım (Lami kalkar) Bir dakika beni dinleyin. Vaktinizin geçeceğinden korkarsanız ücretinize birşey ilave ederiz.\
**Lami** -  Öyle olsun efendim. (Oturur)\
**Necdet** - Affedersiniz. Öteki sandalyeye oturur musunuz? Zira  yanınıza şöylece oturursam daha iyi, daha rahat olacak..\
**Lami** - Hay hay byurun efendim (Yerleşir)\
**Necdet** - Hah şimdi Lami Bey bakın ben altı senedir evliyim. Bu altı sene zarfında karımı aldatmak hatırımdan geçmiyordu. Fakat geçen ay nasılsa elimden bir kaza çıktı.Topu topu bir def'acık karımı aldattım. Bu macerayı size anlatıvereyim. İstinye'den motorla yalnız olarak aşağıya doğru son süratle iniyordum.  Tam Arnavutköyü burnunu döneceğim sırada karşıma birdenbire  zarif bir futa (?) çıkmasın mı?  Beyaz ketenler giymiş.. Kolları buraya kadar (İşaret) kesik, gür lepiska saçlara güneş çarpmış pırıl pırıl yanıyor.. Canlı bir tehlike üstüme geliyor. Aman.. Gözüm kamaşmıştı.. Herşeyden evvel makinemi durdurtmak lazımdı.. Hemen istop ettim dümenimi sancağa aldım fakat ne olsa vakit geçmişti.. Küt! Futasının kıçına çarpmayayım mı?\
**Lami** - Aman yarabbi ne kontakt!\
**Necdet** -  Evet tekneler arasında...\
**Lami** - Sonra\
**Necdet** - Futa bir tığ gibi hafif, belki on metre ileriye kaymasıyla beraber alabora olması da bir oldu..\
**Lami** - Aman!\
**Necdet** - Evet aman!.. Ve tabiî ilk işim bir hamlede havuza düşen bir kelebek gibi deniz içinde çırpınan bu kadını kurtarıp motora almak oldu..\
**Lami** -  Ey sonra..\
**Necdet** - Sonra.. Aygın baygın hanımı futasıyla beraber Bebek'teki yalısına götürdük.. Meğerse nâzeninim pek meşhur bir yeni tüccarın kapatması değil miymiş.. Koca yalıda kimseler yok.. Bir hizmetçi, bir o, bir de ben.. Bana bir izzet ikrâm.. \
**Lami** - Oh.. Oh..\
**Necdet** - Kadın soyundu, kurundu.. Giyindi.\
**Lami** - Sizin yanınızda mı?\
**Necdet** - Evet.. Ama aramızda paravan vardı. Ne ise.. Çay konyak çay konyak birini içip ötekini tokuşturmaya başladık.\
**Lami** - (Gülerek) Oh kontakt kontakt üstüne!.\
**Necdet** - Evet kadehler arasında böyle iki saat geçti.. Siz benim yerimde olsanız ne yapardınız? \
**Lami** - Ne mi yapardım? Kendimi cereyan-ı elektr.. cereyan-ı tabiîye bırakırdım. \
**Necdet** -Gayet tabiî biz de kendimizi akıntıya kaptırdık fakat kahpe kapatma bırakır mı beni.. O gün sarhoşlukla kaptırdığım adresime üç gün sonra bir mektup.. Hem de buraya.. Eve..
**Lami** - Aman.. \ 
**Necdet** - Demeğe kalmadan mektubumu karım okur -zira karım mektuplarımın hepsini açar- işte azizim o günden beri işkence başladı İki saatlik bir rüya hayatından sonra evimde otuz günden beri kâbûs geçiriyorum ne dersiniz? (Sükût) \
**Lami** - Beyefendi müşterimsiniz halinize acırım. \
**Necdet** - Teşekkür ederim... Ama benim halimi tehvîn etmez [kolaylaştırmaz/hafifletmez]. Beni affediniz. Ben ne yapayım bana ne tavsiye edersiniz? Bir plan da bunun için düşünün... \                           
**LAMİ** - Vallahi beyefendi. Bugün yalnız elektrik instalasyonuna dair bir plan yapmaya geldim. Başka bir gün gelir bu sizin sevda instalasyonu için istediğiniz planı da yapmaya çalışırım.\
**Necdet** - Öyle olsun.. Teşekkür ederim.. İşte karım (İkisi de kalkarlar)\

## Yedinci Meclîs

     [Evvelkiler-Pakize (girer)-sonra Pakize]

**Pakize** - (Elinde mecmua ile) İşte Lami Bey kataloğu getirdim. Fakat siz yukarıki köşkü gezmiş miydiniz? \
**Lami** - Hayır efendim..\
**Pakize** - Şu halde evvel orayı bir görseniz.\
**Lami** - Hay hay efendim.. (Necdet'le beraber çıkmaya hazırlanır)\
**Pakize** - Rica ederim beyim Necdet Bey'in size söyleyeceği şeylere zerre kadar ehemmiyet vermemenizi tavsiye ederim. Burada benden başka kimsenin arzusu ve emri olamaz..\
**Lami** - Pek güzel hanımefendi.\
**Necdet** - Elimden bir kaza çıkacak benim!\
**Lami** - Beyefendinin bana yol göstermesine lütfen müsaade eder misiniz efendim?\
**Pakize** - Göstersin..\
**Necdet** - Bahçeye çıkın sola doğru yürüyün geliyorum efendim..\
**Lami** - Peki efendim (Çıkarken çantasıı oturduğu yerde unutur) \
**Necdet** - (Şiddetle karısına dönerek) Bana bak Pakize sâhî söylüyorum sen artık fazla gidiyorsun bu derece olmaz.\
**Pakize** - Ricâ ederim.. (Lami'nin çıktığı tarafı gösterir) \
**Necdet** - Yok.. Artık ben ricâ ederim Pakize. Bunlar ne demek oluyor izâh etmeli (Kapı zili)\
**Pakize** - Kapı çalınıyor sonra daha sonra konuşuruz\
**Necdet** - Hayır şimdi..\
**Zeliha** - Küçük hanım küçük hanım..\
**Pakize** - Ne var Zeliha..\
**Zeliha** - Beklediğiniz geldi..\
**Necdet** - Kim? Hanımın beklediği kim?\
**Pakize** - Hele Zeliha'yı tekdîr etmeyiniz. İyi söyledi beklediğim geldi.. \
**Zeliha** - Evet efendim ya o geldi.\
**Pakize** - Koş getir. Yaşar'dır,  süt kardeşim..\

## Sekizinci Meclîs

     [Evvelkiler-Şemsi]

**Şemsi** - (Kapının önünde gözükür elinde torba tam bahriyeli) Dışarıda bekleyemedim affedersiniz. Ben Yaşar'ım. Pakize Hanım'ın süt kardeşi.\
**Pakize** - Nasıl Yaşar siz misiniz?\
**Şemsi** - Evet süt kardeşiniz.. Karadeniz Sevâhil Kumadanlığı maiyetinden Aytaş Karakol Gemisi aşcısı Yaşar..\
**Pakize** - Yaşar siz ha!..\
**Şemsi** - Evet ben.. Siz de süt kardeşim Pakize Hanım'sınız değil mi?. Kalbim de öyle söylüyordu.\
**Pakize** - Ne güzel çocuk..\
**Şemsi** - (Elindekini yere bırakarak) Müsaade eder misiniz?\
**Pakize** - A.. N demek kardeşim (Şemsi Pakize'yi öpmeye başlar)\
**Necdet**  - Oo.. bu sütü bozuk bu kardeş hâlâ bırakmadı (Öksürür)\
**Şemsi** - Zaten içeriye girer girmez sizi tanıdım. Gönderdiğiniz resim daima yanımda. Buradan ayırmıyorum. (Çıkarır resmi öper)\
**Necdet** - Vay, vay, vay resim de gönderilmiş ha!.. (Öksürür)\
**Şemsi** - (Necdet'e dönerek) Merhaba bahriyeli.. Bu da kim?.\
**Necdet** - Süt hemşirenizin zevciyim.. Necdet..\
**Şemsi** - Ya bizim enişte ha.. Hem bir meslekten ha.. Öpüşelim süt enişteciğim! (Necdet'i öper)\
**Necdet** - Kirpi gibi de batıyor...\
**Şemsi** - (Pakize'ye) Eyy süt kardeşim beni hatırlayabilidiniz mi?\
**Pakize** - Hayâl meyâl Yaşar.\
**Şemsi** - Hayâl meyâl mi.. Bakın ben sizi derhal tanıdım sanki yirmi sene evvel bıraktığım gibi. Mini mini iken şuralarda ne koşar ne oynardık alt alta üst üste. (Çoşup koşar yine öper) Ah benim cici kardeşim yine kavuştuk.. Gelin çocukluğumuzdaki gibi yine öpüşelim!\
**Necdet** - Eyy Yaşar Efendi.. Yeter ya.. Şimdi artık çocuk değilsiniz büyüdünüz değil mi?\
**Şemsi** - Pekala, darılmayın enişte bey ben onun kardeşiyim..\
**Necdet** - Anlaşıldı ya.. Ne ise ne vakit dönüyorsunuz bakalım?\
**Şemsi** - İznim bir hafta demek ki on gün izinliyim!\
**Necdet** -  İyi hesap..\
**Pakize** -  On gün ha.. Ne saadet.. Burada kalırsınız..\
**Şemsi** -  Ma'al-memnuniye.\
**Necdet** - Dur bakalım hanım.. Telaş etmeyin çocuk belki daha serbest bulunmak ister.. Belki İstanbul'da gideceği yer vardır..\
**Şemsi** - Benim kimsem yok ki bir tanecik süt kardesimden mâadâ..\
**Pakize** - Zavallı Yaşar'cık, öyle ya onun başka kimi var? (Şemsi'ye) Burası senin evin Yaşar.. İznin bitinceye kadar burada kal, ye, iç, keyfine bak..\
**Şemsi** - Fena olmaz.. Teşekkür ederim kardeşim..\
**Necdet** -  Ne iyi, bunlar kendi kendilerine gelin güvey oluyorlar..\
**Pakize** - (Zeliha'ya) Zeliha Yaşar'ı balkonlu odaya yerleştirirsin.\
**Necdet** - Balkonlu oda mı? Orası benim odan.. Ben nerede yatarım.\
**Pakize** - Siz arka odada kalırsınız.\
**Necdet** - Hayır biliyorsun, arka oda rutubetlidir Pakize..\
**Şemsi** - Fenâ mı? Kendinizi denizde farz ediniz (Pakize'ye) Yalnız aksilik nerde? Benim değişecek üstüm başım da yok ne çamaşır ne esvap\
**Pakize** - Var var. Kardeşim siz de zevcimin boyundasınız. Onun esvapları size gelir.. Hele iyi oldu tam bu günde onun terziden yeni esvapları geldi.. \
**Şemsi** - Bakın ne tuhaf tesâdüf!..\
**Pakize** - Zeliha beyin yeni esvaplarını süt kardeşime verirsin..\
**Necdet** - A.. Yok.. İşte bu olmaz benim yeni esvabım..\
**Pakize** - Siz de susun (Şemsi'ye) Kardeşim çamaşırınız var mı?\
**Şemsi** - Var ama, üstümde! Başka da yok..\
**Pakize** - Zeliha beyin çamaşır dolabından alırsın olmaz mı?\
**Necdet** - Şimdi de çamaşırlarım.. Ey sonra süt kardeşe biraz da kolonya istemez mi?\
**Şemsi** - (Zeliha'ya) Traştan sonra biraz kolonya verirseniz..\
**Necdet** - Pakize diyorum.\
**Pakize** - Susunuz diyorum. Süt kardeşimin nesi var.. Gül gibi çocuk..\
**Necdet** - Pekala. Biz de diken demedik yalnız..\
**Pakize** - Kâfî.. Senelerden beri deniz üstünde askerlik eden böyle bir kahraman her şeye layıktır. Siz dışarıya! Elektrikçi sizi bekliyor.\
**Necdet** -  Öyle ya ben dışarıya değil mi? Dur sen..(Çıkmak üzere)\
**Şemsi** - (Necdet çıkarken önleyerek) Enişteciğim bana darılmadınız ya.. Gelin öpüşelim..\
**Necdet** - Hayır artık öpüşme yeter.. Yaşar Efendi (Çıkar)\
**Şemsi** - Nesi var. Yoksa buraya gelir gelmez havayı mı değiştirdim..\
**Pakize** - Yok canım siz ona ehemmiyet vermeyin  siz şuraya oturun bakalım, rahat edin. Bakın burada buzlu şurup var içer misiniz?\
**Şemsi** - Hastaya çorba mı soruyor synuz? Hararetim var kardeşim.. Elbette içerim.\
**Pakize** - Alın.. Siz biraz nefes alın bu esnâda biz de odanızı hazırlarız. (Şemsi'nın bıraktığı torbayı alıp Zeliha'ya verir.)\
**Şemsi** - Hay Allah razı olsun sizden.. (Şezlonga oturup sallanırken) İnsan böyle de yaşarmış ha..\
**Pakize** - Evet bazan böyle yaşayanlar hayatlarının lıymetini bilmiyorlar. Haydi Zeliha alık alık bakma  yürü önden (Çıkarlar)\

## Dokuzuncu Meclis

     [Şemsi-Lami]

**Şemsi** - Eyy resm-i kabul mükemmeldi (Düşünür) Adam sen de bir haftalık beylik beyliktir.\ (Şurubunu çeker) 
**Lami** - (Gözükerek) Çantamı nereye koymuşum? Ha işte.. (Şemsi'yi görerek bağırır) Açç Hayırdır inşaallah.. Şemsisen burada ne arıyorsun..\
**Şemsi** - (Kalkarak) Vayy Lami..\
**Lami** - Şemsi'ciğim (Kucaklaşma) Ne vakit geldin? Burada ne arıyorsun?\
**Şemsi** - (Kendi) Vay canına ( Lami'ye) Sus.. Beni ismimle  çağırma!\
**Lami** -  Ne demek.. Yani Şemsi demeyecek miyim?\
**Şemsi** - Sus diyorum. Ben burada Şemsi değilim. Fatih'li elektrikçi Şemsi değilim. Ben Yaşar'ım.\
**Lami** - Ulan yoksa askerden mi kaçtın?\
**Şemsi** - Yok canım. Bir buçuk senedir deniz üstünde imanım gevriyor.\
**Lami** - Eyy?\
**Şemsi** - Eyy'si.. Bizim gemide bön bir arkadaş vardı. Geminin aşcısı Yaşar. Pakize Hanım'ın süt kardeşi imiş.\
**Lami** - Ne.. Bizim yeni müşteriler..\
**Şemsi** - Ya.. Bu Yaşar iki aydan beri süt hemşireşi Pakize Hanım'a benim vasıtamla mektuplar yazar dururdu. İnsan tanımadığı bir kadınla mektuplaşınca tuhaf bir heyecan içinde kalıyor. Sanki mektuplaşan Yaşar değil bendim. Bir gün hanımın resmini istedik. Resim geldi. Nefis. incecik. gül gibi, deniz kızı gibi bir kadın. \
**Lami** - Ay desene resminden deniz kızına tutuluverdin.\
**Şemsi** - Hem de nasıl.. Mecnun gibi. Gece gündüz onu düşünüyorum. Hem düşünebiliyor musun bir buçuk sene süren bir mahrumiyetten sonra..\
**Lami** - Şemsi!\
**Şemsi** - Uzatmayalım. Geçen hagta Yaşar da ben de onar gün izin kopardık. O zaman Leyla'mı görebilmek için delice bir fikre kapıldım. Kendimi Yaşar'ın yerine koyup buraya gelmek vaktinden bir bir hafta çalmak..\
**Lami** - Eyy peki ama Pakize Hanım süt kardeşini tanımıyor muymuş?\
**Şemsi** - Yirmiseneden beri birbirlerini görmemişler..\
**Lami** - Oh oh! Yaşar bu becayişe razı oldu mu?\
**Şemsi** - İster istemez. Allem ettim  kallem ettim. Zaten yufka olan gönlünü yumuşattım. Hem o kadar ki; işi beraberce pişirdik.. İzin tezkeresini de, süt hemşiresinin fotoğrafını da bana verdi. Buraya geldim. Berikiler de yuttu.\
**Lami** - Eyy.. Ulan ya karın! Sen evliydin zannederim.\
**Şemsi** - Karım.. Karım Fatih'te.\
**Lami** - Zavallı kadın da seni bekler durur değil mi?\
**Şemsi** - Hayır zira izin aldığımı kendisine yazmadım. On günlük iznimin yarısını süt kardeşimin yanında geçirmeye karar verdim. Bizimkne de süvarimle aram açıldığını bundan dolayı bana izin vermeyeceğini yazdım. Oyun nasıl? \
**Lami** - Acıklı!.. Vicdansız şey!\
**Şemsi** - Ah Lami'ciğim karımla süt kardeşimin arasındaki farkı bilsen.. biri örekinden bin kat güzel?\
**Lami** - Kim karın mı?\
**Şemsi** - Bırak karımı Allah'ı seversen. Gelecek hafta da ona gider gönlünü alırım. Şimdi sen bana bunlara dair malumat ver. Madem ki müşterilerinmiş!\
**Lami** - Eyy Şemsi'ciğim talihin varmış. Tam zamanında aralarına düştün.\
**Şemsi** - Neden yoksa araları mı açık.\
**Lami** - Sorma kocası süt kardeşini aldatmış..\
**Şemsi** - Nasıl?\
**Lami** - Nasıl mı? Evvela denize sonra ağına düşürdüğü bir kadınla..\
**Şemsi** -Ne süt kardeşim de bunu öğrenmiş öyle mi?\
**Lami** - Evet hanımın mektubunu ele geçirerek.\
**Şemsi** - Aman ne saadet gördün mü? Şimdi işim iş.. Lakin bu kadar güzel bir kadının kocası olup da onu aldatmak..\
**Lami** - Haydi oradan Hint horozu. Ulan sanki sen kendi karını aldatmıyor musun!\
**Şemsi** - Affedersin. Evvela benim karım süt kardeşim kadar güzel değil. Saniyen bir kdın ne kadar güzel olursa olsun kocaları onu aldatmak ezeli bir adet. Sonra herif burada oturmuş mirasyediler gibi askerlik ediyor. Ben bir buçuk senedir Karaddeniz dalgalaroı arasında bocalanıyor[um]. Bu kadarcık bir mükafatım olmasın mı?\
**Lami** - (Gülerek) Hay tilki hay. Ne ise neme lazım. Yalnız dikkat et yakayı ele vermeyesin. Ben senin yerinde olsam bıyoıklarımı kestirirdim. Ey sahi yanağına ne olmuş senin?\
**Şemsi** - Üç ay evvel talim esnasında düştüm yanağım sıyrıldı. Hatta karıma da yazmamıştım.\
**Lami** - Olur şey değil be.. Ne acar şeymişsin.\
**Şemsi** - Sus!.. Süt eniştem geliyor. Birbirimizi tanımıyoruz ha!..\

##     Onunucu Meclis
     [Evvelkiler-Necdet-Pakize-Zeliha]


**Necdet** - Lami Bey çantanızı buldunuz mu?\
**Lami** - Evet efendim. Hanımefendinin verdiği kataloğa bakıyordum. Yarın sabah gelip yukarı köşkün planını yapacağım.\
**Necdet** -Pekala demek şimdi gidiyorsunuz.\
**Lami** - Evet efendim.\
**Necdet** - Buyrun güle güle (Beraber çıkarlar)\
**Şemsi** - (Yalnız) Eyy Şemsi sen budala değilsen Yaşar rolünde yaşarsın. Ben seni tanırırm sen budala bir herif değilsinç Binaenalyh Yaşar rolünde yaşayacaksın.. \
**Pakize** - (Girerek) Kardeşim odanız hazır.\
**Şemsi** -  Ah size nasıl teşekkür edeyim bilmem ki kardeşim..\
**Pakize** - Burası sizin eviniz Yaşar. İsterseniz gelin sizi odanıza götüreyim. (Çıkarlar)\
**Necdet** - (Gelir) Hayır Pakize sevgili süt kardeşinizi Zeliha çıkarsın!\
**Pakize** -  A.. Ne için?\
**Necdet** -  Ben biraz sonra çıkacağım. Kal. Sana birşey söyleyeceğim.\
**Pakize** - Pekala... Zeliha Yaşar'ı götür. Süt kardeşime ne lazımsa verir istirahatını temin edersin...\
**Zeliha** -  Merak etmeyiniz efendim. (Yaşar'a) Buyurun çavuş efendi. \
**Şemsi** - (Çıkarken) Lami'nin hakkı varmış. Tam zamanında düşmüşüm. (Zeliha ile çıkarlar)\

## Onbirinci Meclis

     [Pakize-Necdet]

**Pakize** -  Haydi bakalım ne söyleyecekseniz söyleyin..\
**Necdet** - Evvela san şunu söyleyeyim ki: Yabancıların yanında bana fena muamele ediyorsun.\
**Pakize** - Size daha iyi muamele etmek elimden gelmez. Beni aldatmamalı idiniz.\
**Necdet** - Ben seni aldatmadım. Kendimi bahriye uğruna feda ettim.\
**Pakize** - Ne?\
**Necdet** - Boğulmaktan kurtardığım sefil kadın yazdığı mektupta neler diyordu unuttun mu? Eğer gelmezseniz sizi gazetelerle teşhir ederim. Bahriyeli Necdet Bey bana tasallut diye skandal çıkarırım diyordu. Ben de ne yapayım mesleğimin şerefine siyaneten..\
**Pakize** - Bu rezaleti yaptınız. Beni aldattınız değil mi? Aman yarabbi! Utanmasanız bunun için bir de liyakat madalyası isteyeceksiniz.\
**Necdet** -Liyakat değil ama. Herhalde tahlisiye madalyasına layıktım. 
**Pakize** - Utanmadan bir de alay ediyorsunuz değil mi? Düşünmüyorsunuz ki burada beni müdafa edecek kimsem olmadığı için siz iki kat kabahatlisiniz. Akrabamdan sağ kalan yegane hamim dayım senelerden beri İstanbul'a gelmiyor.\
**Necdet** - Evet yegane haminiz Gazanfer Kaptan. Evlendiğimiz zaman bile lütfen düğünümüzde hazır bulunmaya tenezzül etmediler.\
**Pakize** - Düğünümüz olduğu zaman dayım KArdeniz Filosu'nda
 mühim bir vazife ifa ediyordu. Zavallı adam beni hâlâ mesud zannediyor. Geçen gün ona yazmayı, bana karşı irtikab ettiğiniz hiyaneti  bildirmeyi düşündüm. Fakat babam yerindeki adamı inkisar-ı hayale uğratmak neye yarardı. Sana karşı yapılacak şey, birçok kadınlar gibi, karşıma çıkan ilk erkeğe teslim olmaktı ama... \
**Necdet** - Pakize çıldırdın mı?\
**Pakize** -Allah göstermesin!\
**Necdet** - Ha.. Şöyle biraz nefes alayım..\
**Pakize** - Bu kadar adileşmeyeceğim en muvafık fırsatı bekleyeceğim.\
**Necdet** -  Ne\
**Pakize** - Evet. Fırsat aldatılmış kadınların silahıdır.\
**Necdet** -  Pakize deliliğin lüzumu yok.\
**Pakize** - Sonra [yine] evvelki gibi şen şakrak, muti olacağım. Siz de evin içinde erkek sırasına geçecek hakimiyeti alacaksınız. Bu suretle ödeşeceğiz. \
**Necdet** - (Hiddet içinde) Buna müsaade edeceğimi zannediyorsan...\
**Pakize** - İstersen... Fakat o gün kadar indimde bir gölde, bir hiçten başka birşey değilsiniz. Benim için yoksunuz...\
**Necdet** - (Hala mütehavvir [hiddetli] Ya öyle mi? Peki... (Güya müteessir) Yoksa ne yaparım. Zaten ben beş gün için Cumhuriyet Kruvazörü ile Marmara'ya top talimlerine gideceğim.. Bu sabah enrini aldım. Sana sana söylemeyi unututtum. Hem de şimdi çantamı alıp gideceğim..\
**Pakize** - (Lakayd) Ya pek ala uğurlar olsun.\
**Necdet** - Vedalaşmayacak mıyız? Beni bir defa öpmez misin?\
**Pakize** - Sizi öpmek mi? Sonra. İntikamımı aldıktan sonra..\
**Necdet** - Peki Pakize.. Fakat pişman olacaksın..\
**Pakize** - Acaba?\
**Necdet** - Görürüz.. Allahaısmarladık\
**Pakize** -  Güle güle..\
**Necdet** - (Çıkarken) Hay Allah topunuzu birden (Sesi kaybolur. Bir kapunun şiddetle kapandığı işitilir.\
**Pakize** - (Yalnız. Zile basarak) Gudur bakalım  Necdet Bey. Simdi sıra senin.\

## On ikinci Meclis

     [Pakize-Zeliha-Seha]

**Zeliha** - Zili mi çaldınız küçük hanım?\
**Pakize** - Evet Zeliha! Yaşar'a ne lazımsa verdin ya?\
**Zeliha** - Tabii efendim. Benden ustura istedi. Beyefendininkini verdim.\
**Pakize** - Pek iyi ettin (kapı zili) Git.Kim sorarasa evde yok dersin ha...\
**Zeliha** - Peki efendim..\
**Pakize** - (Yalnız) hay Yaşar hay. (Biraz teessüfle) Ah.. Fakat süt kardeşim.. Hem de bir aşcı\
**Zeliha** - (Girerek) Bir hanım geldi. Sizi yok diyeyim mi?\
**Pakize** - Kimmiş? Komşulardan mı?\
**Zeliha** -  Hayır efendim.\
**Pakize** - İsmini söyledi mi?\
**Zeliha** - Hayır efendim.\
**Pakize** - Peki buraya al. (Gizli) Kimbilir ne için gelmişlerdir.\
**Zeliha** - (Dışarıdan) Evet efendim. Aşağıdalar. Buraya buyurun..\
**Seha** - Mersi kızım.\
**Pakize** -( Seha'yı görüp sevibçle haykırarak) A... Seha.. Seha'cığım.\
**Seha** - (Sevinçle) Cicim... (Kucaklaşırlar) (Zeliha Şemsi'nin tarafından çıkar)\
**Pakize** -Aman yarabbi Seha'cığım sen nereden çıktın. Böyle ahiretten mi geliyorsun?\
**Seha** - Benim güzel Pakize'ciğim görüyor musun altı senelik ayrılıktan sonra yine kavuştuk..\
**Pakize** - Sahi birbirimizi görmeyeli altı sene oldu değil mi?\
**Seha** -  Ya mektepten çıktığımızdan beri... Mektepten çıktıktan sonra hepimiz çil yavrusu gibi dağıldık. İşte yine toplanıyoruz.\
**Pakize** -Aman yarabbi ne mesudum. otursana cicim.\
**Seha** -  Ben iki senedir İstanbul'dayım. Daha önce düşün tamam dört sene Edirne'de kaldım.\
**Pakize** - Niçin?\
**Seha** -  Babmın işlerinden dolayı.\
**Pakize** - Ey şimdi nerede oturuyorsun?\
**Seha** - Fatih'de\
**Pakize** -  İki senedir İstanbul'da olasın da bir kere bana gelmeyesin.. Hain seni..\
**Seha** - Vallahi kardeşim.. Böyle deme. İki senedir evliyim, kaynana yanında oturuyorum. Girdiğime, çıktığıma karışıyorlar.. Bir fırsatını bulamadım. Ama yemin ederim hatırımdan çıkmıyordun. İşte yine evvel seni arayan ben oldum.\
**Pakize** - Sahi öyle. Pekala, adresimi nasıl buldun?\
**Seha** - Pek kolay. Senin Ada'da oturacağını biliyordum. babanın ismiyle köşkünüzü sordum, salık verdiler. Arabacı da sizi biliyor. Adamcağız senin evlendiğini ve kocanın da Necdet Bey isminde zengin bir genç olduğunu söyledi.\
**Pakize** - Ya...(Parmağındaki yüzüğe bakarak) Nihayet sen de evlendin ha..\
**Seha** - Evet iki seneden beri.\
**Pakize** - Kocan kim?..\
**Seha** - Şemsi isminde bir elektrik mühendisi. fakat şimdi asker..Hem de bahriyede\
**Pakize** - Oo.. Benimki de; Necdet de bahriyeyi istemişti.\
**Seha** -İstanbul'da mı?\
**Pakize** - Evet..\
**Seha** - Ah bahtiyarsın Pakize: Şükür et. Kocan yanı başında hem de belki hiç sıkıntısız, tehlikesiz askerlik yapıyor.\
**Pakize** -  Sıkıntısı, teklikesi yok mu?\
**Seha** -  Değil  mi ya?\
**Pakize** -   Ne ise. Sen öyle bil. (Kalkarak) Seha'cığımşurup ister misin?\
**Seha** - Hay hay..\
**Pakize** - (Şurubu hazırlarken) Evvela senin kocandan bahsedelim. Bir sevgi neticesinde mi evlendiniz..\
**Seha** -  Evet bidayette öyle idi.. Fakat sonra askere gidince bu sevgi bir aksülamele uğradı. Gözden ırak olan gönülden ırak olurmuş..\
**Pakize** - A... Niye Seha'cığım..\
**Seha** - İlk zamanlar her hafta muntazamanmektup yazardı. Fakat sonraları.. İki haftada bir. Daha sonraları ayda bir yazmaya başladı.. tasavvur et Pakize'ciğim: gemiye gittiğinden beri bir defa olsun izin alıp gelmedi..\
**Pakize** - Oo.. Vah kardeşim..\
**Seha** - Bir hafta evvel aldığım son mektubunda da suvarisiyle arası açık olduğu için istediği izni reddetiklerini yazıyordu. Düşün, üzüntüden ne yapacağımı bilmiyorum. Nihayet kendi kendime Bahriye Vekaleti'ne müracaata karar verdim..\
**Pakize** - Pek güzel bir fikir..\
**Seha** - Fakat benim vekalette tanıdığım kimse yok. halbuki hatırımda kaldığına nazaran senin bi dayın olacak.. gazanfer Kaptan, pek nüfuzlu bir kaptandır derdin. Acaba onun vasıtasıyla..\
**Pakize** - Ah kardeşim bu şimdi benim de hatırıma geldi ama.. Dayım burada olsaydı ne iyi olurdu. O şimdi kaymakam oldu fakat kimbilir nerededir? Ankara'da mı, İzmir'de mi, Ünye'de mi? Nerededir? O bir yerde durur mu ki.\
**Seha** - Ya vah vah! Halbuki bütün ümidim bunda idi.. (Gördün mü? Bir kere (Düşünerek) Ah keşke ona açıverseydim. \
**Pakize** - Kime?\
**Seha** - Buraya gelirken vapurda yanı başımda büyük rütbeli ihtiyar bir kaptan vardı.. Ona..\
**Pakize** - (Gülerek) İhtiyar bir kaptan mı? Ne söylüyorsun Seha..\
**Seha** - Güzel dinç bir ihtiyar. Vapurda bilhassa yanı başımda oturdu. Aman Pakize'ciğim, daha Sarayburnu'nu bile dönmemiştik, bir de baktım başını çevirmiş tuhaf tuhaf bana bakıyor. Kıpkırmızı oldum. Önüme bakmaya başladım.  Bu sefer de adamcağızın iç çekmelerini işitiyordum. Adamcağız garç garç bir iki defa yutkunduktan sonra, bana dönüp "sıkılıyorsunuz galiba hanımefendi. Buyurun şu gazeteyi. Eğlenirsiniz." dedi. Resimli gazete uzattı.. \ 
**Pakize** - Kabul ettin mi?\
**Seha** - A.. Hiç kabul eder miyim kardeşim? Teşekkürle reddettim. Fakat şimdi pişman oluyorum. Vah vah ..\
**Pakize** -  Dur bakalım üzülme kardeşim. Seha'cığım belki bir çaresi bulunur. Dayım tanıdığı bir başkasını bulalım. Şemsi Bey'e bir izin temin edebiliriz.\
**Seha** - Ah kardeşim bunu yapabilirsen her ikimiz de sana ne kadar minnettar oluruz.\
**Pakize** - Gitmek mi ?Bunca senelik [dizgi hatası] Aman Seha'cığım vazifem; sen akşam buradasın ya.. \
**Seha** - A.. İmkanı yok gitmeliyim..\
**Pakize** - Gitmek mi? Bunca senelik hasretten sonra kırk yılda bir beraberce bir gece geçireceğiz. Reddedersen vallahi darılırım..\
**Seha** - Hayır ama Pakize'ciğim, kaynanam. Bilmem ki..\
**Pakize** - Aman sen de Seha'cığım. Koca kadınsın. Kırk yılda bir bir arkadaşına gece yatısına gitmeye hakkın yok mu?\
**Seha** - Hayır onun için değil. Belki merak ederler diye.. Sizde telefon var mı?
**Pakize** - Hayır daha almadık.\
**Seha** - Şu halde bana müsaade edecekin Pakize'ciğim. Ben Heybeli'ye kadar gidip geleceğim. İki üç saate kadar gelirim.\
**Pakize** - A.. Niçin?\
**Seha** - Görümcem orada oturuyor. Kaynanamın bir işi için onlara uğrayacaktım. Madem ki akşam inmeyeceğim, oradan da Fatih'e telefon ederim. Eczahaneden gelmeyeceğimi söylesinler.\
**Pakize** -  Sen bilirsin Seha'cığım.. (Latife ile) Kaçma ha..\
**Seha** -  A.. Kabil mi Pakize'ciğim?.. (Öperek) Şimdilik Allahaısmarladık.\
**Pakize** - (Seha ile ayrılacağı sırada) Seha'cığımDüşün bakalım mektepten şahadetnamelerimiz alacağımız bahçede ne konuşmuştuk!\
**Seha** - (Düşünerek) Vallahi...\
Pakize  Hatırlayamadın değil mi?  Ondan sık sık bahsediyorduk\
**Seha** - (Gülerek) Ondan sık sık bahsettiğimiz için..\
**Pakize** -  (Gülüşme) Hayır unuttun mu? O  gün bana ne dedin? "Evlendiğim zaman kocam beni aldatırsa ben de ilk fırsatta omu aldatacağım." demedin mi?\
**Seha** - Ha evet kısasa kısas değil mi?\
**Pakize** -Yine o fikirde misin?\
**Seha** - Tabii. Hem bunu yalnız bir intikam usulü değil; adeta bir vazife telakki ediyorum. Eğwer bütün kadınlar bu usulü tatbik edebilselerdi, bugün karısını aldatan kocalar azalırdı.. bak mesela ben Şemsi'yi çıldırasıya seviyorum. Fakat en ufak bir hıyanetini yakalayacak olursam, ona karşı kullanacağım silah budur.\
**Pakize** - Teşekkür ederim Seha'cığım. Bu sözlerin son tereddütlerimi izale etti.\
**Seha** - Ne.. Sakın kocan seni.. \
**Pakize** - Aldatıyor kardeşim.. Evet altı senelik karı kocalıktan sonra.. Bir mektubunu yakaladım ki..\
**Seha** - Vah Pakize'ciğim desene ki bedbahtsın...\
**Pakize** -  Evet fakat intikamımı alacağım. Seha senin nasihatını tutacağım..\
**Seha** - A.. Yok sana nasihat diye söylemedim. Aman Paki[ze] çok düşün ha...\
**Pakize** - Sen olsan bu kadar düşünür müydün?\
**Seha** - Ben başka mesele.. Şimdi senin başında..\
**Pakize** - Ben düşüneceğim kadar düşündüm kardeşim..\
**Seha** - Ne ise düşün de yine konuşuruz Pakize'ciğim. Şimdilik Allahaısmarladık.\
**Pakize** -  Seni geçireyim.. Bilsen ne kadar düşündüm. Bundan başka birşey düşünmüyorum. Şimdi yalnız fırsat bekliyorum.  (Son cümle çıkarken kaybolur.)\

## On Üçüncü Meclis

     [Pakize-Şemsi]

(Bir kaç saniye sonra Şemsi gözükür. Arkasında Zeliha söz söylemektedir.) (Şemsi tamamen traş olmuş, sivil giyinmiştir. Elinde serpuş vardır.)

**Şemsi** - Sizin beyin esvabı sanki bana göre yapılmış o kadar iyi geldi ki.. Al kızım.. Şunu da pencereye as biraz hava alsın.. (Serpuşu astıktan sonra kendisini hayran hayran seyreden Zeliha'ya bakıp gülerek) Bu kılıkla da hiç gemi aşcılarına benzemiyorum değil mi, Zeliha?\
**Zeliha** - Ooo.. Hayır efendim hiç..\
**Pakize** - (İçeriden seslenerek) Zeliha! Zeliha!\
**Zeliha** -  Aaa.. Küçük hanım (Süratle koşarak) Efendim..\
**Pakize** -Neredin sen? Yaşar indi mi?\
**Zeliha** - Evet efendim burada (Tamam bu sözde Pakize sahneye girer)  (Şemi'yi yeni kılıkla görüp şaşırarak)\
**Pakize** -A.. Siz misiniz? Vallahi tanıyamayacaktım,
 Yaşar.. Siz ha.. \
**Şemsi** - Evet ben Yaşar. Biraz evvelki nefer kıyafetinden çıkınca beni tanımakta güçlük çektiniz değil mi?\
**Pakize** - Hakikaten öyle. Hele bıyıklarınızı kestikten sonra..\
**Şemsi** -  Bu yeni elbise ile bütün bütün değiştim..İğrenilmeyecek konuşulacak bir adam oldum değil mi?\
**Pakize** - Hayır onu demek istemiyordum..\
**Şemsi** - Ne deseniz haklısınız. Bir gemi aşcısının giyinip kuşandıktan sonra bu derece değişmesine ben de olsam şaşardım.\
**Pakize** - Sahi soracaktım.. Askere girmezden evvel asıl mesleğiniz de aşcılık mıydı? \
**Şemsi** - Yoo..\
**Pakize** - Pekiyi nasıl oldu da?..\
**Şemsi** - (Bir pot kırmamak için) Ha.. Yani bilirsiniz ya.. Valideniz merhûm beni.. Şey.. Hastahanesinin aşcıbaşısı..\
**Pakize** - Hastahane mi ya?.. Mektep.. Dar'ül-hayır..\
**Şemsi** - Öyle ya.. Hastahane demişim.. Dar'ül-hayıra aşcı Ömer Ağa'nın yanına evlatllık olarak vermiş. Bizim babalığın yanında mutfak işlerini biraz öğrenmiştim. Sonra gemide en kolay iş olarak bunu bulduğum için mutfağa inmeyi kendşm istedim. Askerliğim bitinceye kadar bu yağlı meslekte kalmaya ahd ettim. Yoksa mutfak bemin midemi doyursa bile dimağımı doyuramayacağı için..\
**Pakize** - (Birden sözünü keserek resmi bir şive ile) Rica ederim Yaşar Bey otursanıza.. Rahatsız olmayınız..\
**Şemsi** -  Teşekkür ederim efendim. Fakat benimle niçin böyle birden bire resmi oldunuz, kardeşim?\
**Pakize** - Çünkü.. Nasıl söyleyeyim bilmem.. Demin karşımda sadece bir nefer, bir asker görmüştüm.. Bir askerin karşısında kendimi daha ziyade emniyette hissediyordum. Halbuki şimdi..\
**Şemsi** - Şimdi sivil olarak gördüğünüz halde kendinizi daha mı az emniyette hissediyorsunuz?. Bana gelince asker, sivil sizin karşınızda aynı şeyi hissediyorum.. (İskemlesini yanaştırarak) asker veya sivil Trabzon'dan buraya kadar yalnız sizi görmek için gelen Yaşar'dan başka birşey değilim.. Yaşar, çocukluk arkadaşınız Yaşar.. İki aydan beri kendisine en hararetli, en samimi mektupları yazdığınız, resminizi gönderdiğiniz Yaşar.. O andan itibaren sizin için hayatını fedaya hazır olan..\
**Pakize** - (Birden silkinerek) Rica ederim..\
**Şemsi** -  (Cümlesini süratle  itmam ederek [tamamlayarak]) hazır olan süt kardeşiniz Yaşar!\
**Pakize** - (Önüne bakarak) yaşar Bey bu tarzda konuşmayınız..\
**Şemsi** - Bey mi? Oldu mu ya? sadece Yaşar.. Süt ninenizin oğlu Yaşar.. Son mektubunuzda ne diyordunuz? Senelerden sonra karşınıza çıkan size hayatınızın en mesut safhası olan çocukluğunuzu hatırlatan, küçüklük arkadaşınız, yegane dostunuz değil miyim?\
**Pakize** - hay hay... samimi dostum, süt kardeşimsiniz..(Bunu söylerken gayrı iradi olarak elini uzatmıştır.)\
**Şemsi** - (Pakize'nin elini alıp kalbine götürerek) Ben de ben de sizin en samimi dostunuzum.\
**Pakize** -(Değişik bir sesle) Yaşar elimi bırakınız benim..\
**Şemsi** - (yavaşca bırakırken içine bakarak)  Peki affedersiniz.. Ooo! Aman Yarabbi! eliniz..\
**Pakize** -  Ne var bir şey mi gördünüz?\
**Şemsi** - Evet bir şey gördüm. Keşke görmeseydim..\
**Pakize** - Merak ettiriyorsunuz..\
**Şemsi** - hayır.. Merak etmeyin.. Çok garip. Keşke görmeseydim. (Elini bırakır)\
**Pakize** - (Elini uzatarak) ne var? Kuzum ne gördünüz..\
**Şemsi** -Ne mi gördüm. Elinizde öyle şeyler okudum ki..\
**Pakize** - Nasıl? Okundunuz mu? El falından anlıyor musunuz?\
**Şemsi** - (Gülümseyerek) Eh bir parça.. Eğer fala inanırsanız size oradan muhim şeyler haber verebilirim.\
**Pakize** - (Gülerek) Acaba!.. Haydi bakalım..\
**Şemsi** - Şüphe mi ediyorsunuz?. Peki.. Hayır sağ değil sol elinizi verin.. (Elini alır içine bakarak) İşte şu hat saadeti gösterir. Bakınız ne kadar kısa. Şuradan kesilmiş. Saadetiniz devam etmemiş. Siz artık mesut değilsiniz. Çünkü zevciniz sizi aldatıyor..\
**Pakize** - (tam hayretle) Nasıl bildiniz?..\
**Şemsi** - Eliniz söylüyor. Doğru değil mi?\
**Pakize** - Doğruysa bile size ne?\
**Şemsi** - Durun, durun, işte işte deniz üstünde bir kaza! Yayılmış [Dizgi hatası-Bayılmış] güzel bir kadın kocanızın kolları arasında ah.. eğer bir pertavsız [büyüteç] olsa size kocanızın ismini de, kadının gözlerinin rengini de söyleyebilirdim. \
**Pakize** - Aman Yarabbi! Siz falcı mısınız acaba?\
**Şemsi** -Bazan falcı da olurum. Durun bakayım. Ooo.. Kokulu bir mektup (Elini koklar gibi ağızına sürerek) evet bu eliniz titreyerek mektubun bir parçasını yırtıyor.. Herşeyi biliyorsunuz. Kocanızı affetmediniz. hakkınız da ver. Çünkü sizi aldatmak..\
**Pakize** - (elini çekerek) Yeter Yaşar..\
**Şemsi** - Affedilmez bir cinayet. Sonra kıymet bilmez koca o adi kadının etkilerine kapılmış vaktiyle aynen size söylediği tatlı cümleleri, yeminleri sayıp dökerken; uzaklarda, denizaşırı ufuklarda zavallı bir adam gecelerini sizi düşünmekle geçiriyordu. \
**Pakize** - Yaşar neler söylüyor sunuz?\
**Şemsi** - Evet zavallı bir adam..  El yazılarını kalbi çarparak tekrar tekrar okur, resminiz öpücüklere boğardı.\
**Pakize** - Yaşar Bey..\
**Şemsi** - Pakize Hanım.\
**Pakize** - Yaşar Bey süt kardeşimsiniz.\
**Şemsi** - Evet süt kardeşim. Süt kardeşciğim sizi seviyorum.\
**Pakize** - (Mübhem [belli belirsiz] tekrarlar) Ben seviyor.. (Şemsi'ye) Süt kardeşinizi bu tarzda nasıl seviyorsunuz? Günahtan korkmuyor musunuz?\
**Şemsi** - Kimbilir beni size bu kadar yaklaştıran şey de annemin verdiği sütlerdir. Sonra ne yalan söyleyeyim ben sizin bütün bütün süt kardeşiniz değilim!\
**Pakize** - (Kalkarak) Nasıl?\
**Şemsi** - (Devamla) Ben sizin üvey süt kardeşinizim!..\
**Pakize** - Ne demek?\
**Şemsi** -  Evet üvey! Eğer ben de sizin annenizden süt emseydim o vakit öz süt kardeş olurdum. Hem sonra mürur-u zaman var. O bir çocukluk hatırası idi. Görüyorsunuz ya? Sizi seviyorum. Yazdığınız her mektup bu sevgiyi kıvılcımladı. Ah! Sizin bu derece bedbaht olduğunuzu bilseydim bütün bunları size evvelden yazardım.\
**Pakize** - Keşke yazsaydınız. Size cevap vermezdim bu günahı da işlemezdik..\
**Şemsi** - PakizeHanım kalbiniz emin olsun: Bu günah değil.. Sevgiye susamış ruhların arasına ne süt ne yoğurt girer.\
**Pakize** -  Aman Yarabbi!..\
**Şemsi** - emin olun yarın öbür gün gemiye gittiğim zaman beni orada teselli edecek şey yalnız bu sevgidir. Bırakınız da hayatımın en güzel hatırasını alayım..\
**Pakize** - (Dalgın fakat mütehayyic [heyecanlanmış]) Aman yarabbi! Süt kardeşimle..\
**Şemsi** - Hayır.. Süt kardeşinizle değil, gönül arkadaşınızım. Bir an için unutun bu süt kardeşliğini\
**Pakize** - (Aklına kocası gelerek) İşte fırsat. (Şemsi'ye) Peki süt kardeşim.\
**Şemsi** - Ah süt kardeşim sizi seviyorum. (Zaten kolları arasında tuttuğu Pakize'yi alır dudaklarından öper bu puse mütekabil bir inilti içinde devam eder.)\

## On Dördüncü Meclis

     [evvelkler - Gazanfer Kaptan]


**Kaptan Kaymakam** - (Dipten gözükür. Onları bu halde görünce gür bir sesle bağırır) Lâşkâ [halatı boşa al]... (Şemsi Pakize derhal ayrılır.) Ha sizi tehlikeli bir vaziyette yakaladım çocuklar.\
**Pakize** - (Hayretle bağırır) A.. Dayım!\
**Şemsi** -  Vay bir kaymakam [yarbay]. (Sivil olduğunu unutarak askeri bir vaziyet alır)\
**Ka[ymakam]** - Şu anda aklınızdan geçmiyordum. Ya, sürprizim tam zamanında oldu. Ne donakaldınız orada? (Kollarını açarak) Kızım Pakize'm gel bakayım. Dayını böyle mi karşılayacaksın bakayım...\
**Pakize** - (Kollarının arasına koşarak) Dayıcığım..\
**Ka[ymakam]** - Evladım..\
**Şemsi** - Dayısı mı? Vay canına...\
**Ka[ymakam]** - Öp bakayım dayını.. Hadi hadi kocan müsaade eder. (Şemsi'ye) öyle değil mi sevgili damadım?\
**Şemsi** - (Rica ederek) Kocası mı? Eyvah! Kocası mı olduk?\
**Pakize** - (Kendi) Ne?! Kocam zannediyor...\
**Ka[ymakam]** - (Pakize'nin değişik mahcup halini  görerek) Ey ne var ya?\
**Pakize** - A.. Bir şeyim yok dayıcığım. Sizi birdenbire görmek beni şaşırttı da.\
**Ka[ymakam]** - Adam sen de. İşte kavuştuk. Öp bakayım da bir daha dayıcığını. (Pakize onu öper) Hah... (Onu bir daha öperek) Oh biricik kızım! Kocan kadar ateşli öpemiyorsun değil mi? Sizi gidi külhaniler sizi. Demin şurada sımsıkı maçuna olmuştunuz. Lakin sevgili damadım karınıza bir sarılışınız var. Aranızdan su sızmayacağına bahse girerdim. Tam sapına kadar beraber gelmişsiniz. (Elini uzatarak) Sizinle nihayet tanıştığıma emin olun pek memnunum. Bilseniz düğününüzde bulunamadığıma ne kadar müteessir oldum. \
**Şemsi** - (Sürat-i intikal ile [durumu hemen kavrayarak]) Ah.. Ya ben? Bütün gün süt... Süt dökmüş kedi gibi sessiz duran Pakize'ye "Hanım dayınız gelmeyecek mi?" diyerek sizi dilimden düşürmedim. Nihayet ikimiz de üzüldük...\
**Ka[ymakam]** - Yavrularım... Geldim.. Mesud olduğunuzu gözümle gördüm. ama heyhât bu sefer yanınızda uzun müddet kalamayacağım. Yarın sabah Ankara'ya gideceğim. Daha İstanbul'a gidip kendime öte beri düzeceğim..\
**Pakize** - (Geniş nefes alarak) Ya... Böyle hemencecik mi dayıcığım? \
**Ka[ymakam]** - Evet yavrum... vekalet acele çağırmış. Verilecek pek mühim raporlarım var. Eh, Allah bilir ama yine bana uzun bir sefer görünüyor.. Galiba vapur teslimine gideceğiz.\
**Pakize** -   Ya vah vah..\
**Şemsi** -    Ya vah vah.. \
**Ka[ymakam]** - Bu sefer Karaburun'dan gelirken kendi kendime İstanbul'a varınca mutlaka Ada'ya gidip çocukları öpeceğim diye ahd ettim. Burada bir öğle yemeğinizi yer, hemen kaçarım.\
**Şemsi** - Ya.. Ne güzel fikir değil mi Pakize'ciğim?\
**Pakize** - A tabii tabii.\
**Ka[ymakam]** - Fakat ben boyuna kendimden bahsettim. Biraz da size daie konuşalım canım. (Oturarak)  Bir defa ikinizin mesut olup olmadığınızı sormak fazla. Çünkü sizin gibi altı senelik evliler dört günlük nişanlılar gibi sarmaş dolaş olunca pek belli ki..\
**Pakize** - Aman dayıcığım..\
**Ka[ymakam]** - Haydi canım! Kızaracak ne var deli kız.? Bilakis hoşuna gitsin. Harpten sonra böyle kocalar ender oldu.. (Şemsi'ye) Zaten göreyim seni delikanlı, istersen onu mesut etme; sonra benim elimden zor kurtulursun..\
**Şemsi** -  (Ne söyleyeceğini şaşırarak) Teşekkür ederim.. Şey tabii beyefendi.\
**Ka[ymakam]** - Kızım her türlü saadete layıktır. O ismet ve namusun timsalidir.\
**Şemsi** -  Hakkınız var beyefendi.\
**Ka[ymakam]** - Beyefendi, beyefendi! Gemide miyiz be! Dayı diyemiyor musunuz? Dayı...\
**Şemsi** - (Gülerek) Hakkınız var dayı bey, hakkınız.. \
**Ka[ymakam]** - Hah şöyle eyy. Az kaldı unutuyordum. Sizin askerlik daha bitmedi mi? Yine liman dairesinde misiniz?\
**Şemsi** - (Şaşırarak) efendim?\
**Pakize** - (Atılarak) Evet dayıcığım. tabii yine orada. Size de yazmıştım ya...\
**Ka[ymakam]** - Pek güzel pek güzel! Fakat tuhaf şey. pakize'nin bana gönderdiği bahriye elbiseli resimle sizin aranızda iyice fark var.\
**Şemsi** - Evet o vakitlr şimdiki arasında fark var.. Ben zaten çabuk şişmanlar, bazan da derhal zayıflarım... Gününe göre..\
**Ka[ymakam]** - (Gülerek) Gününe göre mi? Hah hah pek tuhafsınız...\
**Pakize** - (Kalkıp mukalemeyi [konuşmayı-sohbeti] değiştirerek) Dayıcığım şurup içer misiniz? \
**Ka[ymakam]** - (Şemsi'ye) Şurup değil ama şarap varsa...\
**Şemsi** - Şarap var değil mi, Pakize ?..\
**Pakize** - Var ya.. Vereyim dayıcığım..\
**Ka[ymakam]** - Eh pekala. Ben de sıhhatinize içkinizi içerim..\

## On Beşinci Meclis

     [Evvelkiler-Necdet-Zeliha]


**Necdet** - (Arkasından gelen Zeliha['ya] hiddetle] Sna gitmeyeceğim diyorum. Kızım al şunu (Şapkasını verir) Bana biraz sıcak su hazırla.. Limana telefon ettim. yarın sabah ilk vapurla inerim.\
**Ka[ymakam]** - (Şarabı içip bardağı iade ile) Oh fena değil bu şarap. Nereden böyle..\
**Necdet** - (Kaymakamı görerek) Vay bir kaymakam. (Gayrıı iradi olarak pencerenin yanında asılı duran serpuşu giyer. Hazır ol vaziyeti alır)\
**Şemsi** - İşte şapa oturduk!\
**Ka[ymakam]** - Bu neci?\
**Pakize** - Bu şeyci dayıcığım... Süt ninemin oğlu Yaşar...\
**Necdet** - Bu ne diyor?\
**Ka[ymakam]** -sizin yaninizdami\
**Şemsi** - Evet.\
**Pakize** - (Kocasına gider süratle) Bana uy yoksa bittik.\
**Necdet** - Ne?..\
**Pakize** - (Dayısının yanına gelerek) Dayıcığım Yaşar izinle gelmiş. Ay Taş gemisinde aşcı.\
**Necdet** - Şimdi de aşcı olduk..\
**Ka[ymakam]** - (Amirane) Yaklaş bakalım aşcı başı...\
**Şemsi** - (Kendi) Benim başlığı almış..\
**Ka[ymakam]** - (Okuyarak) Aytaş'tansın ha.. Ver elini bakayım.\
**Necdet** - Elim pek piste efendim.\
**Ka[ymakam]** - Zarar yok uzat.\
**Necdet** - (Bileğini indirerek) Buyurun efendim\
**Ka[ymakam]** - Eyy? Doğru Trabzon'dan mı geliyorsun?\
**Necdet** - Galiba.\
**Ka[ymakam]** - Ne demek galiba?\
**Pakize** - (Necdet'e işaretle) Söylesene Yaşar. Bu sabah gelmedin mi? (Dayısına) Kusuruna bakma dayıcığım. Sizi görünce şaşaladı.\
**Necdet** - (Şiddetle) Evet evet Trabzon'dan geliyorum efendim. Doğruca Trabzon'dan.\
**Ka[ymakam]** - Belli leş gibi kokuyorsun.\
**Necdet** -Leş gibi mi?\
**Ka[ymakam]** - (Necdet'i iterek) Şu hale bak! Bu da gemici ha?.. Ayakta durmaya mecali yok. Böylelerini de gemide ne diye kullanırlar bilmem ki. (Şemsi'yi göstererek) Halbuki bak şuna: Topuz gibi delikanlı! \
**Necdet** - Şimdi bayılacağım.\
**Pakize** - Bir bardak daha ister misiniz, dayıcığım?\
**Ka[ymakam]** - Hay hay kızım (Necdet'e) Söyle bakalım geminiz karakola çıkıyor mu?\
**Necdet** - karakola hayır efendim.\
**Pakize** - (Atılarak) Dayıcığım yemekten evvel biraz istirahat istemez misiniz?\
**Şemsi** - Yorgunsanız benim odama buyurun.\
**Necdet** - Odana mı?\
**Ka[ymakam]** - Dinlenmek değil ama bir parça elimi yüzümü yıkaraım\
**Pakize** - (Dışarı bağırarak) Zeliha! Zeliha!\
**Şemsi** - Zeliha! Zeliha!\
**Necdet** - Herif evi gibi emrediyor.\
**Zeliha** - Efendim.\
**Pakize** - Zeliha dayımı tuvalet odasına götür.\
**Zeliha** - Peki efendim.\
**Ka[ymakam]** - Haydi bakalım kızım düş önüme (Çıkar)\

## On Altıncı Meclis

     [Kaymakamdan maada- evvelkiler]
     
**Şemsi** - (Onlar çıkarken) Ben galiba doğrudan doğruya eve gitmediğime pişman olacağım\
**Necdet** - (Başındaki serpuşu atarak) Of.. Gitti.. Şimdi siz bu oyunu bana izah eder misiniz?\
**Pakize** - (Mülayimetle) Hay hay azizim.\
**Necdet** - ey bu kaymakam dayın değil mi?\
**Pakize** - Öyle ya .. Birdenbire geldi Yaşar'ı da sen zannetti.\
**Necdet** - Ben yani kocan?\
**Pakize** - Evet..\
**Necdet** - Ya.. Ben ben de..\
**Şemsi** - Sizi de beni yani süt kardeşini zannetti.\
**Necdet** - Niçin doğrusunu söylemediniz?\
**Pakize** - Niçin mi? Söyleyemezdim çünkü tam içeriye girdiği sıra süt kardeşimle öpüşüyordum.\
**Necdet** - (Hiddetle) Nasıl?..\
**Şemsi** - (Hiddetle) Necdet Bey burada bir kabahatli var..\
**Pakize** - (Necdet'i göstererek) O da budur.\
**Necdet** - Ben miyim?\
**Şemsi** -Sizsiniz..\
**Pakize** - Sensin ya.. Bütün bunlar senin başının altından çıktı. O kabahati işlemeye idin bu karışıklıklar olmazdı.. Size vaad etmemiş miydim? İlk fırsatta intikamımı alacağım diye.\
**Necdet** - Eh demek bu fırsat..\
**Pakize** - (Şemsi'yi gösterek) Fırasat da budur.\
**Necdet** - Siz misiniz?\
**Şemsi** -(Tefehhürle [övünerek]) Benim.\
**Necdet** - Desenize tam zamanında gelmişim.. (Hiddetle) evvela siz aşcıbaşı Yaşar Efendi... İlk işiniz buradan arabanızı çekmek olsun.. Hem derhal..\
**Pakize** - hayır. Ben buna müsaade etmem.\
**Şemsi** - Süt kardeşim müsaade etmiyor.\
**Necdet** - (Kendini kaybedercesine) Pakize diyorum!\
**Pakize** - Dayım onu sizi zannediyor. Mümkün mü? Zaten o bu akşam gidiyorç Üçümüzün de selameti için Yaşar'ın akşama kadar benim kocam olarak kalması lazımdır.\
**Necdet** - Ben de kapı mandalı olacağım öyle mi? Katiyen! Anlıyor musun? Katiyen! Dikkat et sonra ona herşeyi söylerim.\
[**Pakize** -] Bana hıyanet ettiğini duyarsa seni seni affetmez. Ben de ona karşı aldatılmış bir zevce vaziyetinde kalamam. Bunu bil.. \
**Şemsi** - (Necdet'e) NMüsaade edin de en bi-taraf hükmü ben vereyim.\
**Necdet** - (Şiddetle) Siz susun bakalım bulaşıkcı efendi...\
**Şemsi** - Peki bana göre hava hoş. Siz düşünün.\
**Necdet** - (Karar vererek) Ne olursa olsun. Herşeyi kabul ederim, bu vaziyeti asla...\
**Pakize** - Pekala. Sonra başına gelecekleri de düşün.\
**Necdet** - Bundan başka daha ne gelebilir.\
**Pakize** - İşte dayım...\

## On Yedinci Meclis

     [Evvelkiler- Kaymakam- Zeliha]

**Necdet** - Kaymakam Bey size birşey söylemek isterim...\
**Pakize** - (Sağda) Ben de size birşey söylemek isterim dayıcığım.\
**Necdet** - Affedersiniz evvela ben söyleyeceğim..\
**Ka[ymakam]** - Eyy dur bakalım sen aşcıbaşı! Sana müsaade ettiğim zaman söylersin! Haydi alabanda marş!\
**Necdet** - Fakat müsaade ediniz Kaymakam Bey..\
**Ka[ymakam]** - Ne? Bana cevap mı veriyorsun. Sen hiç talim ve terbiye görmedin galiba! Burada evinde olmadığını unutuyorsun. Haydi bakalım. Aö başı aşcıbaşı! Şöyle gelin damadım yaklaşsın da Pakize..\
**Şemsi** - Peki dayı bey...\
**Ka[ymakam]** - Sevgili yavrularım... Beni dinleyin. Ben tekaüd edildiğim günden itibaren Karaburun'daki çiftliğe çekilip oturacağım. Pek muhtemeldir ki bu akşam sizi öpüp ayrıldıktan sonra bir daha birbirimiz görmeyelim.\
**Pakize** - Ne söylüyorsunuz dayıcığım?\
**Ka[ymakam]** - Kesme yavrum... Söyleyim de.. Dört sene evvel küçük çiftliğimde bulunan simli kurşun madenine bu sene şirket talip oluyor. Beş yüz bin lira veriyor.\
**Necdet** - (Yüksek sessle) Yarım milyon...\
Kaymakam  - Susun arkadan (Pakize'ye) Çiftliğimden maada bu servetimi ikiye taksim etmiş, bir hissesini sana, bir hissesini İzmir'de oturan öteki teyzen Hatice'ye terk etmeye karar vermiştim. (Ayağa kalkarak) İstanbul'a gelmeden evvel onlara da uğrayıp bir akşam kaldım. Ah onların hayatı ile sizinki arasında müthiş bir fark var. Burada kucaklaşma, öpüşme, sevişme, saadet; orada her dakika dırıltı, gürültü eksik değil... Kocası Hatice'yi aldatıyor. Hatice de kocasını. İşte bunun için vasiyetimde Hatice'ye metelik bırakmayacağım. Hepsini size bırakacağım. \
**Necdet** - (Kendini kaybedercesine sevinerek) Oh yaşa....\
**Ka[ymakam]** - Sana ne oluyor aşcıbaşı? Sus bakalım! (Pakize'ye) Ey Pakize'm buna ne dersin?\
**Pakize** - (Mahcup) dayıcığım, güzel dayıcığım bu kadar lütfunuza ne diyeceğimi bilemiyorum. Pek minnettarım.\
**Ka[ymakam]** - Siz ne dersiniz damadım?\
**Necdet** - (Yine dalarak) Ne diyeceğim? Allah razı olsun derim.\
**Ka[ymakam]** - Buna da mı karıştınız Yaşar Efendi?\
**Şemsi** - Dayı beyciğim bilmem ki size nasıl teşekkür etmeli...\
**Ka[ymakam]** - O teşekkür nafile yavrum. Beni memnun etmek isterseniz daima sevişin...\
**Necdet** - Oh oh bari vasiyeti de ben yazayım.\
**Ka[ymakam]** - (Devamla) Sizden bundan başka birşey istemem. E artık vasiyetten ölümden daha ziyade bahsetmeyelim. İnşaallah bu dediğim servete mümkün olduğu kadar geç sahip olursunuz... (Pakize'ye) Haydi bakalım. Bana söyleceğin şey ne imiş...\
**Necdet** - Hiç. Hiç efendiö.\
**Ka[ymakam]** - Yine mi? Bu sizin süt ninenizin oğlu da mutfak sineği gibi herşeye burnunu sokuyor..\
**Necdet** - Affınızı rica ederim kaymakam bey. Bana soruyorsunuz zannettim de...\
**Ka[ymakam]** - Kes! Yeter! Pakize, senin söyleyeceğin ne imiş bakalım..\
**Pakize** - Oo dayıcığım ehemmiyetsiz birşeydi. Biraz evvel söyleyecektim ama bilmem, unuttum.\
**Ka[ymakam]** - Ya sen? Yaşar? (Necdet dalgınlıkla Şemsi'ye bakmaktadır) Yaşar! Yaşar, diyorum dalga geçme..\
**Necdet** - Ha? Ben ni kaymakam bey..\
**Ka[ymakam]** - Evet sen. Demin birşey söylemek için müsaade istemiştin. Müsaade ediyorum. Haydi söyle şimdi..\
**Necdet** -Ben mi kaymakam bey? Bir yanlışlık var efendim. Benim size söyleyecek hiçbir şeyim yok.\
**Ka[ymakam]** - (Şiddetle Şemsi'ye) Bu heri alimallah bunak galiba..\
**Şemsi** - Galiba dayı bey..\
**Ka[ymakam]** - Sen aklını ocağa mı düşürdün be herif... (Bu esnada Zeliha elinde bir takım kağıtlar vardır- ağlar gibi burnunu çeker.)\
**Ka[ymakam]** - Nen var kız?\
**Necdet** - (Kendi) Eyvah bu kız bir pot kırmasın. (Pakize'ye işaretle)\
**Zeliha** - Ben mi efendim. Şu kağıtları bahçey götürüp [a]tacağım..\
**Ka[ymakam]** - Ey peki bunun için mi ağlıyorsun?\
**Zeliha** - hayır efendim. Deminden küçük hanımı görmek için bir kaç gün izin istedim de o da evde kimse kalmayacak diye bana izin vermemişti. Çünkü aşcı da nişanlısına gitti. Şimdi ben de nişanlıma gitmek istiyorum da küçük hanım bir türlü izin vermediği için..\
**Ka[ymakam]** - Ey peki kes zırlamayı. (Pakize'ye) Pakize'ciğim bu kıza üç gün izin vermiyor musun?\
**Pakize** - A.. Dayıcığım reddetmemiştim, bu akşam gitme diye söylemiştim.. İzin vermez olur muyum?\
**Zeliha** - (Elindeki kağıtları bırakır. Sevinçle yüzü güler) Ah, sahi mi küçük hanımcığım...\
**Necdet** - Haydi artık durma git.\
**Şemsi** - Hemen koş. Durma haydi..\
**Şemsi** -(Kızı önleyerek) Haydi işte durma çık. Çabuk çık.\
**Necdet** - (Apar) Aşcıbaşı Yaşar bize yemek yapar (Yüksek) Yaşar.\
**Necdet** - (Kaymakam için düşünerek Şemsi'ye bakarak) Kaymakam gitse de evimi çorbaya çeviren şu aşcıyı bir def etsem..\
**Ka[ymakam]** - Yaşar buraya gel..\
**Şemsi** - Baksana buraya Yaşar. kaymakam bey birşey emrediyorlar.\
**Necdet** - Ha affedersiniz efendim.\
**Ka[ymakam]** - (karşısında resm-i tazimde bulunan Necdet'e) Aşcı kadın izinli imiş. Hizmetçi de gitti. Onların yerin bana öğleye güzel bir omlet yapmalı..\
**Necdet** - Ben mi efendim?\
**Ka[ymakam]** - Hayır ben. Sen ne biçim aşcısın be?\
**Necdet** - Affedersiniz
 efendim. Omlet.. Omlet değil mi efendim?\
**Şemsi** - Yaşar biraz dalgındır efendim (Yaşar'a) Haydş bakalım Yaşar. Süt kardeşinin evi senin evin demektir. Sıva kolları.\
**Pakize** - Evet evet.. Haydi bakalım kardeşim, dayıma güzel bir omlet yap..\
**Ka[ymakam]** - Miskin mendebur, haydi bakalım. Topla şu kağıt parçalarını yerden..\
**Şemsi** - Yaşar goster kendini, sen aşcı değil misin?..\
**Necdet** - Ben aşcıyım ama gemide...\
kaymakam - Ne armut adam şu yarabbi.. Gemini çok seviyorsan şimdi oraya gönderirim ha..\
**Pakize** -   Haydi, haydi Yaşar.\
**Şemsi** -   Haydi, haydi Yaşar.\
**Ka[ymakam]** - Çabuk diyorum koş miskin herif.. (Birden kağıtları toplamakla meşgul Necdet'in arkasına bir tekme vurur.)\
**Necdet** - (Süratle çıkarken) Koşuyorum efendim.. Aman yarabbim! Ben şimdi mutfakta ne halt ederim..\

Perde iner





